# filename: config.toml
[database]
host = "localhost"
database = "trafficviolationsystem"
user = "root"
password = ""
secret = "trafficviolationsystemjwt"

[server]
port = ":8000"

[servicecommunication]
port="5000"